### ISSUE TITLE
Feature Req: UX: Autofill Main Stat for Weapon, Helmet, and Armor

### ISSUE THREAD

**Issue by Mystic7AuDJa** [fribbels/Fribbels-Epic-7-Optimizer#1]
Since these values are static it would make the most sense when selected for the Main Stat selection to auto populate with: 
Attack for Weapon
Health for Helm
Defense for Armor

**Comment by fribbels** [comment]
Hi, I'm a bit confused which option you're talking about. There isn't anything for selecting weap/helm/armor main stats because they never change, so I'm not sure which option you want autofilled?

**Comment by Mystic7AuDJa** [comment]
Thank you for following up. I'm referring to the Main Stat section under the Edit and Add New Items, I've included a few screenshots for ease of explanation. 

![image](https://user-images.githubusercontent.com/51798584/103427524-98268580-4b8f-11eb-8cc7-ca2e34acd328.png) 
![image](https://user-images.githubusercontent.com/51798584/103427543-b7bdae00-4b8f-11eb-82bc-3bfabfa4f778.png) 
![image](https://user-images.githubusercontent.com/51798584/103427546-bf7d5280-4b8f-11eb-9781-de88c11da3c6.png)

Would be a great asset for those of us that manually enter the gear due to physical devices capturing photos at larger sizes.

**Comment by endqwerty** [comment]
+1 to this. Those stats are guaranteed so you can probably just lock the Main Stat dropdown for those item types.

**Comment by fribbels** [comment]
Will be in 1.3.0
