### ISSUE TITLE
Fails to generate 4p lifesteal sets for previously unequipped characters.

### ISSUE THREAD

**Issue by NullTamer** [fribbels/Fribbels-Epic-7-Optimizer#103]
When a character has no gear and a search is run for 4p lifesteal, no results are created. Tested with previously equipped characters under identical parameters, and across multiple characters, with equipped items toggled on for all.

**Comment by fribbels** [comment]
Hi, could you show a screenshot of the whole optimizer page when this issue happens? Would help me to see the other filters

**Comment by NullTamer** [comment]
![image](https://user-images.githubusercontent.com/40069350/133373935-5ad763bf-540d-41f4-819e-0738177b3330.png)
![image](https://user-images.githubusercontent.com/40069350/133373956-3018866c-6a72-4962-bffe-18f80ee94a4b.png)

Top character Ungeared. Tested other ungeared characters as well. Bottom Character Geared. This issue only happens with lifesteal, any other set bonus searches like normal.

**Comment by fribbels** [comment]
Hi, this might be a hero priority issue? It looks like you only have 3 necks/4 rings/5 boots to work with on the top screenshot so it might not be able to find a build with those filters. If you uncheck hero priority can you find a build for tsurin?

**Comment by NullTamer** [comment]
Unchecking Hero priority has fixed the issue. Many thanks.
