### ISSUE TITLE
Feature Request: New storage scanning

### ISSUE THREAD

**Issue by numbahs** [fribbels/Fribbels-Epic-7-Optimizer#105]
You probably know already, but the new storage that SmileGate created doesn't get scanned when using the automatic importer. It just omits those gears and when I am trying to merge, any gear that is in there will no longer show up since the automatic importer thinks I fed them probably.

**Comment by fribbels** [comment]
Hi, if you do a regular scan but after loading into the lobby, open the storage before hitting Stop scanning, it will pick up the storage items
