### ISSUE TITLE
Feature Request: Ability to set hero level for proper stat calculations

### ISSUE THREAD

**Issue by danecurbow** [fribbels/Fribbels-Epic-7-Optimizer#11]
At the moment all heros are assumed level 60 and 6 awakened. Being able to set their level and awakening would be nice. For the most part it could be restricted to just setting level 50/60 and 5/6 awakened.

**Comment by fribbels** [comment]
This one's on the todo list - I'll try to get it done it in either 1.4 or 1.5

**Comment by fribbels** [comment]
..or 1.6, sorry lol
