### ISSUE TITLE
Feature Request: can equip gear to hero from gear page

### ISSUE THREAD

**Issue by GameXLife** [fribbels/Fribbels-Epic-7-Optimizer#12]
some equips can be used, but it will be ignored from filter even I set top to 98%
(i.e I just want the 10 speed on a LV65 gear, but its value is only 250 or below let it be ignored by filter)
So I hope I can equip it to hero manually.

**Comment by fribbels** [comment]
The way to equip gear manually is through the Gear tab -> Edit selected item -> Equipped
