### ISSUE TITLE
Issue with using GPU-Optimization

### ISSUE THREAD

**Issue by Jackieee-CS** [fribbels/Fribbels-Epic-7-Optimizer#127]
I'm trying to use the GPU-Optimization on my CPU, (running a ryzen 7 3800x, GTX 3070), and when I'm using the GPU-optimization setting enabled I'm noticing it use 100% of my CPU, and then freezing, and spitting out a ton of errors. 

Tried running it in admin mode, and it seems to be an issue purely related to running it with GPU optimization. Was hoping for any solution or help on this ! Thank you very much

**Comment by Jackieee-CS** [comment]
Just adding onto this, I tried to turn on GPU hardware scheduling on windows 10, (it did not change anything), tried updating my java and reinstalling it to java 64-bit as per the get-started (it did not change anything), as for the error messages, I am getting a lot of "java.lang.outofmemory error", something about heap space. I am wondering if it is because my permutation numbers are too high or something.

**Comment by fribbels** [comment]
Hi the java subprocess caps at 4gb, you’re likely hitting that limit when your # of search results gets close to 5 million. Add more filters to reduce your search results

**Comment by Jackieee-CS** [comment]
Thank you very much! That seems to have been the issue, and applying stricter filters fixed the problem!
