### ISSUE TITLE
Feature Request: Language Support for other Languages than English

### ISSUE THREAD

**Issue by Reikokaz** [fribbels/Fribbels-Epic-7-Optimizer#14]
Add Languages which are supported from Epic 7
(German, Chinese, Japanese, ...)

**Comment by fribbels** [comment]
I probably will not be doing this anytime soon - the OCR is very difficult to get working well enough in English, and would be even harder to do for every language. As long as players are able to switch to English for screenshots it should work fine for them. (except for the Japanese server unfortunately)

**Comment by CSOLYOO** [comment]
Can we use lang file to make localization easier? I can provide zh-CN lang support.

**Comment by xiewl** [comment]
This optimizeris very powerful。I suggest use OCR for importing data and use localization file for interface

**Comment by cwt9562** [comment]
we need i18n for UI， no need for OCR

**Comment by cwt9562** [comment]
i think you can provider an i18n by a javascript lib
then we can add our languages

**Comment by fribbels** [comment]
Tracking progress here https://github.com/fribbels/Fribbels-Epic-7-Optimizer/issues/38
