### ISSUE TITLE
Feedback on equipment score calculation

### ISSUE THREAD

**Issue by alexpung** [fribbels/Fribbels-Epic-7-Optimizer#15]
Hi congrats on writing this great program, just a comment on the score calculation

Score = Attack %+ Defense %+ Hp %+ Effectiveness+ Effect Resistance+ Speed * (8/4)
+Crit Damage * (8/7)+ Crit Chance * (8/5)+ Flat Attack / 39 * 0.5+ Flat Defense / 31 * 0.5+ Flat Hp / 174 * 0.5

This penalize the flat stats way too much imo, as a lot of characters can actually make great use of flat stats. 
e.g. tama with hp
Tama at lv 60 fully awakened has 4370 hp, so 43.7 flat hp would equal to 1% hp
according to the formula the equipment score 1 point for every 348hp, which is the same as 1% hp, I suppose 174 is a "full roll", so is it missing a multiplier?

I propose the following formula for Flat stats

Flat Attack / 11     (it assume you put it on a character with 1100 atk)
Flat Defense / 6.5 (it assume you put it on a character with 650 def)
Flat Hp / 55 (it assume you put it on a character with 5500 hp)

I also propose the main stats of the equipment added to the score so equipment of different levels can be compared.

**Comment by fribbels** [comment]
Yeah I noticed this the other day too - I meant to use a multiplier of (8 * 0.5) but only used 0.5 instead. I think what I'm going to do is go through all the units and get the average health/def/atk and use the average to calculate the flat -> percent equivalent score. TBD soon

**Comment by fribbels** [comment]
Score calculation fixed in 1.4.0. Using this column as percent equivalent stat values, based on average stats of 5 * heroes

![https://i.imgur.com/vlXewHn.png](https://i.imgur.com/vlXewHn.png)
