### ISSUE TITLE
Feature Request: Support import from e7-tools OCR website

### ISSUE THREAD

**Issue by VerTiGoEtrex** [fribbels/Fribbels-Epic-7-Optimizer#17]
Check out https://e7gears.herokuapp.com/ (the source is [here] (https://github.com/e7-tools/gear-reader)).

It's decently robust at exporting gear information. The key advantage is it imports from videos rather than screenshots, and it supports most screen resolutions, meaning those of us who don't use emulators can use it.

However, the format of the JSON file is the same as the format Zarroc's optimizer imports from.

From his readme:

>Can import JSON file from /u/HyrTheWinter's Optimzier, so you won't have to input all your gear again if you used it in the past

AFAIK, this is the format that e7gears exports in as well. This feature request is to add support for this json format. Thanks!

**Comment by fribbels** [comment]
I will probably not work on this, as there's a bunch of different gear readers and I don't want to have to support them all - would rather use the effort to improve the OCR ability in the optimizer. Also I think there's a slightly roundabout way to do this already, would be to use the e7gears reader -> import it into the Zarroc optimizer -> export a file there -> import it into this optimizer.

**Comment by VerTiGoEtrex** [comment]
>improve the OCR ability

@fribbels, or be a god and write a packet decoder like you already did ;)
