### ISSUE TITLE
Merging storage items

### ISSUE THREAD

**Issue by santiago-henao-12** [fribbels/Fribbels-Epic-7-Optimizer#186]
I read the instructions, but I don't find how to make this work. Whenever I try to merge data from the file that has my storage gear data (since it seems you have to do 2 separate scans) it just overwrites my gear. I don't know how to have both my general items and the stored ones.

Edit: To clarify, I import my gear.txt with my normal import info through the merge data button in the Import heroes and gear automatically. It all works fine, and my heroes have the data of their equipped gear. Then I import the gear_1.txt where only my items in storage were saved, using the Merge Data option again, what happens is that my gear is replaced by the stored items **only** and my heroes appear naked.

**Comment by Joy97D** [comment]
I think what you should try doing is not make 2 different gear.txt files u can just make one which will contain the all the gears ( general + storage).
After u log in to the game open up equipment storage and click stop scanning it should take contain both of types of gears general + storage.  It works for me.

**Comment by santiago-henao-12** [comment]
Well it doesn't work that way for me. Tough luck, if I do that, it only imports the storage ones.

**Comment by Joy97D** [comment]
Ah yes Sometimes the scan doesn't work properly and doesn't take the storage ones. Sometimes i need to do the process 2-3 times to get the required result.
