### ISSUE TITLE
1.2.1 / 1.3.0 / 1.4.0 are all dead

### ISSUE THREAD

**Issue by i-eat-plexiglass** [fribbels/Fribbels-Epic-7-Optimizer#19]
![image](https://user-images.githubusercontent.com/44297655/107668327-8d671200-6c5e-11eb-9478-8109e96b28bf.png)

Above image shows up across all 3 versions I've downloaded. 

Can I suggest a safe mode that triggers and is guaranteed to work even when updates or something causes a snafu / there's no internet?

**Comment by fribbels** [comment]
Hi, can you check if you have Java 8, 64 bit installed? This looks like a java problem from the error messages.

**Comment by i-eat-plexiglass** [comment]
![image](https://user-images.githubusercontent.com/44297655/107703273-6c67e680-6c89-11eb-9fe6-100e64109211.png)
This isn't the first time I've had problems either. I'm not sure if the java version I have is bugged or something.

**Comment by i-eat-plexiglass** [comment]
Somehow, rerunning the java installation file (without uninstalling the existing version) fixed the problem. There's probably something wrong with my computer.
