### ISSUE TITLE
Missing Hero: Fairytale Tenebria

### ISSUE THREAD

**Issue by Mystic7AuDJa** [fribbels/Fribbels-Epic-7-Optimizer#2]
Noticed she was missing from the list of heroes, figured it was worth mention.

**Comment by KillerBotK** [comment]
If this is like the previous optimiser I used then it pulls hero stats via epicsevendb.com and that doesn't appear to be keeping units up to date at the moment. Mort still isn't on there for example. 

If you want to build FTene via the optimiser then just put her in as Sage Bal as they share same stats and awakenings for now. Hopefully epicsevendb.com starts updating again soon though.

**Comment by Mystic7AuDJa** [comment]
Appreciate the workaround, will play with it more.

**Comment by fribbels** [comment]
Yep the data is being pulled from epic7db so as soon as this is updated it will get picked up by the app: https://github.com/EpicSevenDB/gamedatabase
