### ISSUE TITLE
BUG: Set bonus for only 3 pieces of Destruction Set.

### ISSUE THREAD

**Issue by luchibobra** [fribbels/Fribbels-Epic-7-Optimizer#20]
![2021-02-12_17-24-23](https://user-images.githubusercontent.com/10171930/107768819-ddc29a80-6d58-11eb-9faf-75766dc0905a.png)
Actualy all stats except Critical Hit Damage is correct, but Critical Hit Damage is higher by 40% (destruction set?): 165 base cd + 131 by equip = 296cd.

**Comment by luchibobra** [comment]
Just checked on random character, and now i am sure, 3 piece of destruction set always apply a set bonus.

**Comment by fribbels** [comment]
Whoops that's my bad, changed the destruction set logic last patch and used a 3 instead of 4. Will update in the next version. Will consider if this needs a 1.4.1 hotfix

**Comment by fribbels** [comment]
Fixed in 1.4.1
