### ISSUE TITLE
UX Request: Reduce 0's in Max Optimization textbox (enable visual cues)

### ISSUE THREAD

**Issue by endqwerty** [fribbels/Fribbels-Epic-7-Optimizer#22]
Love the work you've been putting into this.

Small thing that I think would help prevent easy typos is to change the Max Optimization results into units of 1k instead of asking the user to type of the full value. I always worry when I have that many 0's to type out since there's no visual cue.

Example: `5000000` -> `5000` (units of 1k)

An alternative is to maybe have a label that adds commas next to it when the user clicks out of the textbox or something.

However, this is probably very very very low priority since most users shouldn't ever even need to change that value.

**Comment by fribbels** [comment]
Fair suggestion, I think I'll probably just bump this to multiples of 1k as an easy fix

**Comment by fribbels** [comment]
Done in 1.6
