### ISSUE TITLE
Request; Add option to set default save location

### ISSUE THREAD

**Issue by KillerBotK** [fribbels/Fribbels-Epic-7-Optimizer#23]
I think moving saves out of the core folder is a great idea however I actually run mine via a Onedrive sync folder (so I can alter it at work, on the road, etc.) and it's a pain that every time I go to save it defaults to my Documents and I have to remember to change it.  If we could specify the default save location that would be perfect.  Thank you.

**Comment by fribbels** [comment]
Adding to todo list for 1.5

**Comment by fribbels** [comment]
Released in 1.5
