### ISSUE TITLE
Request: Alphabetize Hero List in 'Gear: Equip / Edit Item' Subsection

### ISSUE THREAD

**Issue by Pariah** [fribbels/Fribbels-Epic-7-Optimizer#25]
First of all, thank you very much for your work. It is appreciated.

I had a small request. I was wondering if the Hero List under 'Equipped' in the 'Equip / Edit Item' area in the 'Gear' tab could have their names resorted like you have done on the Optimizer tab. Preferably, having the option to start typing in the name would be great as well but beggars can't be choosers!

I've included an image in case I am not being clear.

Thank you for your time!

<img width="1040" alt="gearEquipEditItem" src="https://user-images.githubusercontent.com/616394/108253421-c0f6e000-7127-11eb-87eb-2a8f6f2f6e4a.png">

**Comment by fribbels** [comment]
Oh yeah, I forgot about that one. Will change it with v1.5

**Comment by fribbels** [comment]
Released in 1.5
