### ISSUE TITLE
Request: Manually add the required reforged material type of LV85 equipment.

### ISSUE THREAD

**Issue by CSOLYOO** [fribbels/Fribbels-Epic-7-Optimizer#27]
I found that equipment data imported by screenshot can get the type of reforged material. 
But we cant manually add this to equipment. 
If we can , It would be more clearly to decide whether to reforge equipment.

**Comment by fribbels** [comment]
This will be added in 1.5

**Comment by fribbels** [comment]
Released in 1.5
