### ISSUE TITLE
Unable to add new item in Gear tab after failing

### ISSUE THREAD

**Issue by jmnoguera** [fribbels/Fribbels-Epic-7-Optimizer#3]
When the "Add New Item" pop-up is filled wrongly and displays the error "Please make sure Type... are not empty" the input boxes from this pop-up and any future pop-up of this type are not clickable/fillable.

**Comment by fribbels** [comment]
Should be fixed in 1.2.0/1.2.1 - alert() popups are no longer used and are replaced by custom popups that dont mess up input boxes
