### ISSUE TITLE
Error : Unable to load/save optimizer data

### ISSUE THREAD

**Issue by KY-Aegis** [fribbels/Fribbels-Epic-7-Optimizer#30]
Hi and thank you for making this great app. I was trying to import my autosave.json file from V1.3 to the newer versions using the save/load all optimizer data but both the save data and load data button has the "Waiting for file" text and doesn't seem to trigger any pop-up to select the file. So I tried to re-upload my screenshots and manually insert my hero stats but when I close the app all of my heroes and equipment seems to be missing but this only happens when I am using V1.4 and V1.5. and it works normally for V1.3. Is there anything I can do to fix this?

**Comment by fribbels** [comment]
So when you click "Load data" there's no popup at all? Are there any errors messages on startup? If you could open the developer tools and show me a screenshot of any red errors in the console, that would be helpful. Ignore the yellow warnings.

**Comment by KY-Aegis** [comment]
Hi, there seems to be no error code popping up anywhere but I have screen recorded my problem for your reference. https://youtu.be/RYy5QAuCbR8

**Comment by fribbels** [comment]
Ok I see now. The dev tools screenshots would be super helpful here to locate the issue

https://i.imgur.com/3LsXncp.png

https://i.imgur.com/ocNlNTV.png

**Comment by KY-Aegis** [comment]
Here you go
https://imgur.com/a/qvyZN6Z

**Comment by fribbels** [comment]
Could you try making a folder called FribbelsOptimizerSaves inside of C:\Users\User\OneDrive\Documents\

Looks like its trying to make the folder but failing to do so

**Comment by KY-Aegis** [comment]
Oh its fixed now. Thanks for the assistance. But its kind of weird as it runs okay on version 1.3 but still thank you regardless and keep up the great job!
