### ISSUE TITLE
Feature Request: pause calculation

### ISSUE THREAD

**Issue by EzekyleA** [fribbels/Fribbels-Epic-7-Optimizer#32]
If I do a calculation with many Permutations that needs hours to finish, let me pause it and resume if I need to do something else in the meantime, so I won't have to cancel it and start over.

Maybe an option for limited CPU use would also be helpful, so CPU usage won't be at 100% all the time it calculates.

Thank You

**Comment by fribbels** [comment]
In general, if you're running a search that takes more than like 10 minutes, you're probably doing something wrong with your filters. Can you share a screenshot of what you're trying to search for that's taking so long?

**Comment by EzekyleA** [comment]
I came up with this and my other post while figuring out my fastest possible equip.

![Neue Bitmap](https://user-images.githubusercontent.com/30778653/109418005-5a46b180-79c6-11eb-9765-f8c7a213b7e9.jpg)

This took about 25 minutes to calculate.
While yes certainly I could reduce the Top % more, I decided I don't want to, so I won't miss a possible combination.

**Comment by fribbels** [comment]
Hi, top 50% is very unnecessary - you will get the same top results with top 10-20%
