### ISSUE TITLE
Failled to call subprocess: 

### ISSUE THREAD

**Issue by withoutacomb** [fribbels/Fribbels-Epic-7-Optimizer#33]
[](url)
![image](https://user-images.githubusercontent.com/54373909/109394653-184e3a80-78f6-11eb-9a44-39122cedb082.png)

**Comment by withoutacomb** [comment]
I got this after trying to replace data with the textfile that was made.

**Comment by fribbels** [comment]
Hi this looks like a java startup issue. The dev tools screenshots would be super helpful here to locate the issue

https://i.imgur.com/3LsXncp.png

https://i.imgur.com/ocNlNTV.png

And show any red errors you find

**Comment by h1ghroll3r** [comment]
I'm actually having the same issue. He's the dev tool screenshots from my end:

https://imgur.com/a/ACvhXP3

**Comment by fribbels** [comment]
Its probably an issue with your java installation? Looks like the java subprocess isnt getting loaded. Try uninstalling your current java version then reinstalling it from https://java.com/en/download/manual.jsp using the Windows Offline (64-bit) offline installer - and then restarting your computer after

**Comment by fribbels** [comment]
Closing this issue since its p old, check out the discord channel for faster tech support. https://discord.gg/rDmB4Un7qg
