### ISSUE TITLE
Speed EE for rose not doing anything

### ISSUE THREAD

**Issue by jpanda109** [fribbels/Fribbels-Epic-7-Optimizer#34]
When specifying an EE for Rose, the stats don't change to reflect the EE's stats. I've tried reloading and force reloading the page.

**Comment by fribbels** [comment]
You're right, looks like the speed EEs are bugged - Yuna has the same problem

For now, use this section for her speed EE

![https://i.imgur.com/Vx0OduA.png](https://i.imgur.com/Vx0OduA.png)

**Comment by fribbels** [comment]
Done in 1.6
