### ISSUE TITLE
Main stat from auto-import set to max

### ISSUE THREAD

**Issue by endqwerty** [fribbels/Fribbels-Epic-7-Optimizer#35]
Auto-imported gear has main stat set at lvl 85 +15 enhance stats. Ideally, they get set to the current stat (some of those enhancement levels are wrong as the actual level is higher, not sure if that's intended or if you want a separate issue for that) or if not current, then the expected stat for an item of that enhancement level.

![Screenshot 2021-02-28 212512](https://user-images.githubusercontent.com/714349/109455430-7456b300-7a0b-11eb-8071-81e292ec9ea2.png)

Regarding the enhancement level issue, these are my weapons. I'm on windows  bluestacks v5 beta. not 100% sure if python3 is installed, but it looks like things worked correctly so I assume it is. npcap is 100% installed.
![image](https://user-images.githubusercontent.com/714349/109455527-b8e24e80-7a0b-11eb-9388-68eb6a7d246c.png)

**Comment by fribbels** [comment]
That is intended - so that the optimizer can use them as if they are +15 stats. Otherwise you would never see +12/+9/etc pieces because they lack so much of the main stat

**Comment by endqwerty** [comment]
I see, make sense on both points. I suggest adding something similar to the warning that some items might be level 0 to inform users that these items will be set to max main stat values. Maybe, also note that items enhancement levels are going to be rounded down to 3,6,9,12 but at this rate you'll probably solve the problem quick enough that more text isn't necessary. 

TBH, for me, I don't see much value in using these items when pretending their main stat is maxed out. For a lot of my units, these main stats matter and are part of I'm trying to min/max to get additional usable units. I haven't done the math though, so I trust your opinion if you say that its really not important.

**Comment by fribbels** [comment]
Yeah I see your point - its not "currently" optimal, but a lot of endgame players use the optimizer to decide what gear to upgrade. For example, if you're optimizing a build and a +12 item shows up in the results, that's a good indication that you should finish +15ing that item - as that build can only get better.
