### ISSUE TITLE
java child process exited with code one 

### ISSUE THREAD

**Issue by coup3** [fribbels/Fribbels-Epic-7-Optimizer#39]
![image](https://user-images.githubusercontent.com/79882424/109579024-4d53ca80-7b4c-11eb-899a-a4498790f561.png)
![image](https://user-images.githubusercontent.com/79882424/109579040-504ebb00-7b4c-11eb-991b-ead94dea16e2.png)

**Comment by fribbels** [comment]
Hi, could you show the console tab?

![https://i.imgur.com/lGLfPUg.png](https://i.imgur.com/lGLfPUg.png)

**Comment by bearstronautical** [comment]
I had the same issue when I tried this program today. I just had to install 64-bit Java for Windows from the Java website. Hope this helps.

**Comment by fribbels** [comment]
For reference, use https://java.com/en/download/manual.jsp, and download the Windows 64-bit offline installer

**Comment by fribbels** [comment]
Closing this issue since its p old, check out the discord channel for faster tech support. https://discord.gg/rDmB4Un7qg
