### ISSUE TITLE
Issue with Pre Release 1.2.1

### ISSUE THREAD

**Issue by KillerBotK** [fribbels/Fribbels-Epic-7-Optimizer#4]
It would appear I have some gear missing stats as I'm constantly bombarded with errors every time I go to optimise.  Is there any way of identifying which piece of gear is missing stats so I can sort?  It pretty much renders this version unusable so going to drop back to 1.2.0 for now.

**Comment by KillerBotK** [comment]
![image](https://user-images.githubusercontent.com/58690746/103476520-91c22480-4dae-11eb-9280-ac77f0963170.png)

**Comment by fribbels** [comment]
Can you add me on discord at fribbels#7526? Would be easier to discuss. Also if you could send me the save file I can take a closer look

**Comment by fribbels** [comment]
Resolved - due to item only having 3/4 substats on import from Zarroc's optimizer. Will fix error message in next version to be more informative
