### ISSUE TITLE
Request: Automatically scan which Hero has the Gear equiped

### ISSUE THREAD

**Issue by Somaxax** [fribbels/Fribbels-Epic-7-Optimizer#40]
The new Scanner introduced in version 1.5 is amazing. Only thing I'm missing is to also know what Hero has that Gear equiped. It takes a lot of time to manualy assign every gear a Hero, but I realy want to know how has that gear without having to jump into the game. An ofc I want to be able to exclude some Heroes gear from the search. I personaly did it manualy cause I realy want that information, but I'm sure for most ppl thats too much effort.

**Comment by fribbels** [comment]
I got this request a lot this week, so this is on the todo list for probably 1.7 or 1.8

**Comment by InitialDet** [comment]
This! Please!

**Comment by MoRooz** [comment]
Really need this one, please high priority

**Comment by nuqz1** [comment]
Imo one of the most important features. The optimizer is not really usable without it. 

I tried it but every time i want to regear my units i will always have moved some pieces here and there in-game and having to adjust that in the optimizer by hand is just a waste of time. So I have to start over from scratch again. I want to use my unit builds that i perfected with the optimizer + in-game adjustments as a basis and i want to lock units that i have finished bulding and tuning.

In a perfect wolrd you will build all your units in the optimizer and adjust everything in it, but thats never going to happen.
