### ISSUE TITLE
CP for heroes in tool are ~.83x actual

### ISSUE THREAD

**Issue by Brhinosaur** [fribbels/Fribbels-Epic-7-Optimizer#45]
Hello, amazing app you've created!
I would like to report a possible bug in which the CP for the heroes do not show up accurately in the tool. For instance, my Sigret is 6* 6-awak, with EE and artifact all accounted for via the bonus stats. All stats match between the tool and the game except for CP, which seems to be off by a factor of .83 roughly. I have noticed the same with my G. Purr., also 6 star 6 awak, which was also off by a factor of roughly .83.
Thank you for looking into this, and keep up the great work!

![image](https://user-images.githubusercontent.com/46721046/110007353-2f1ed380-7ce0-11eb-8b4c-83137fe9c82e.png)
![image](https://user-images.githubusercontent.com/46721046/110007184-0bf42400-7ce0-11eb-91a1-7e6cf51bbeaf.png)

**Comment by fribbels** [comment]
Hi there, the CP in the optimizer doesn't account for skill enhances at the moment, which is where the discrepancy is. However the optimizer CP is relative to stats, so the highest CP in the optimizer will be the highest CP on your unit.

**Comment by Brhinosaur** [comment]
That makes perfect sense. Thank you very much!
