### ISSUE TITLE
Not able to use auto import

### ISSUE THREAD

**Issue by magaries** [fribbels/Fribbels-Epic-7-Optimizer#47]
Sadly I've been unable to use the auto import feature despite installing everything correctly and being on a 64bit windows operating system. Could it have something to do with the update that E7 pushed yesterday (which also made it so LDplayer wasn't working with E7 for a little bit). It just gives me the failed to import items message. Any idea what could've caused this?

**Comment by fribbels** [comment]
[scanner.txt](https://github.com/fribbels/Fribbels-Epic-7-Optimizer/files/6088959/scanner.txt)
Try downloading this scanner.txt file, renaming it to scanner.py, then replacing the existing scanner.py within your install folder/data/py

There's issues with some people's machines with how the network data is being read - this is my best attempt to resolve it so far

**Comment by kether82** [comment]
The old scanner didn't work with my bluestacks but is working well so far with this one. Not op, but came here to say that it works.

**Comment by magaries** [comment]
Sadly, it still didn't work. Maybe there's something wrong with my connection then

**Comment by fribbels** [comment]
Could you open the developer tools 

![https://i.imgur.com/G6ySooY.png](https://i.imgur.com/G6ySooY.png)

then open the console tab

![https://i.imgur.com/zZZGkT8.png](https://i.imgur.com/zZZGkT8.png)

scroll down, then leave it open and run a scan - then screenshot the console for me. Lets see if there's any other errors

**Comment by zx900930** [comment]
I'm using nmap 7.80 and the scanner is working with bluestacks latest version.
![image](https://user-images.githubusercontent.com/734749/110200491-99f61900-7e5e-11eb-934e-f2f5b7de03cc.png)

Since it's not using adb bridge to communicate with the emulator but directly captures the network packeges. It should be compatible with any android emulators?

**Comment by fribbels** [comment]
Yes any android emulator - even shared connection through Mobile Hotspot from phone works too.

**Comment by magaries** [comment]
Evidently after coming home today, booting up my pc and trying again it works. Which is weird since in the process of originally trying to get it to work I'd rebooted it about 5 times. So I guess this is resolved, thank you!
