### ISSUE TITLE
Feature Req: Predict reforges for 85 lvl gear with +9/+12 enhancement

### ISSUE THREAD

**Issue by djinnkesta** [fribbels/Fribbels-Epic-7-Optimizer#5]
For now predict reforges works only for 85 lvl gear with +15 enhancement. But there are a lot of potentially good non +15 gear (I add to optimizer something valuable at least +9). If there is technical difficulties with predict substat reforges of non +15 gear, it would be good to see and use in calculations predict reforges of main stat.
![изображение](https://user-images.githubusercontent.com/77228776/104120761-7aed7600-534a-11eb-89d0-62e701b1ee01.png)
P.S. Thanks for your hard work!

**Comment by fribbels** [comment]
Hmm that's a good idea, I'll add predicting non +15 gear to the todo list but it'll be fairly low prio for now. Have to change the reforge logic to not require all 4 stats. (sick boots btw)

**Comment by fribbels** [comment]
Will be released in 1.4.0. Thanks for the idea!
