### ISSUE TITLE
Add instructions for using physical Android devices to generate screenshots

### ISSUE THREAD

**Issue by bankzed** [fribbels/Fribbels-Epic-7-Optimizer#6]
Found a reasonable method to generate the screenshots of gear for physical Android devices using adb, 
[Scrcpy](https://github.com/Genymobile/scrcpy), and batch files:

1. Install applications for remotely controlling device:
   * [Scrcpy GUI](https://github.com/Tomotoes/scrcpy-gui#install)
   * Or [guiscrcpy](https://github.com/srevinsaju/guiscrcpy#installation)
2. [enabled adb debugging](https://developer.android.com/studio/command-line/adb.html#Enabling) and make sure you can connect to the device with Scrcpy GUI or guiscrcpy
3. Windows users can follow these [instructions](https://gist.github.com/bankzed/0ef9902582b2cec05bc8c15af3429576#gistcomment-3588575) to set the proper resolution, create, and use a screenshot hotkey.
* Macs users can follow a general guide from [here](https://gist.github.com/bankzed/0ef9902582b2cec05bc8c15af3429576#file-using_android_device_for_gear_optimizer-md)

TODO:

- [ ] Verify the steps outlined here work for other users 

- [ ] Create Bash script for Macs to set the display/density and hotkey for screenshots

These are the resulting screenshots and filtered images from a physical Android phone (OnePlus 5t) that did not meet the 1600x900 and 240dpi requirements but was overrode to work:
![1](https://user-images.githubusercontent.com/77178933/104120938-61274100-5300-11eb-9d0a-b6c6c3f3f0a0.png)
![1 pngdebugLevel](https://user-images.githubusercontent.com/77178933/104120940-64223180-5300-11eb-8f00-c0c7a41bd036.png)
![1 pngdebugSubstats](https://user-images.githubusercontent.com/77178933/104120941-64223180-5300-11eb-8e16-2ef473902c7c.png)
![2](https://user-images.githubusercontent.com/77178933/104120942-64bac800-5300-11eb-8770-a77e4f7acfd6.png)
![2 pngdebugLevel](https://user-images.githubusercontent.com/77178933/104120944-671d2200-5300-11eb-806a-b73ed2deff32.png)
![2 pngdebugSubstats](https://user-images.githubusercontent.com/77178933/104120945-67b5b880-5300-11eb-824a-678b382fc726.png)
![3](https://user-images.githubusercontent.com/77178933/104120946-684e4f00-5300-11eb-86c3-fea1e56e15c0.png)
![3 pngdebugLevel](https://user-images.githubusercontent.com/77178933/104120949-6ab0a900-5300-11eb-9a97-816d26e852f5.png)
![3 pngdebugSubstats](https://user-images.githubusercontent.com/77178933/104120951-6b493f80-5300-11eb-9264-ddd8f037278d.png)
![4](https://user-images.githubusercontent.com/77178933/104120952-6be1d600-5300-11eb-9ba3-19aecb7eef0c.png)
![4 pngdebugLevel](https://user-images.githubusercontent.com/77178933/104120954-6e443000-5300-11eb-8fe0-0af8ca5528cf.png)
![4 pngdebugSubstats](https://user-images.githubusercontent.com/77178933/104120955-6e443000-5300-11eb-8017-816e82769840.png)
![5](https://user-images.githubusercontent.com/77178933/104120957-713f2080-5300-11eb-802f-c389c49d0574.png)
![5 pngdebugLevel](https://user-images.githubusercontent.com/77178933/104120960-743a1100-5300-11eb-88ea-9976afdbe8da.png)
![5 pngdebugSubstats](https://user-images.githubusercontent.com/77178933/104120961-743a1100-5300-11eb-863d-753ad556363c.png)

**Comment by fribbels** [comment]
I'm going to pass on working on this one, with the auto importer in play now
