### ISSUE TITLE
v1.6 Gear tab bug: Enhancement level filter buttons not working

### ISSUE THREAD

**Issue by bokdelajungla** [fribbels/Fribbels-Epic-7-Optimizer#61]
For what I've seen, +6 button filter shows +15 gear, +3 button filter shows +12 gear, and the others show no gear at all.

**Comment by fribbels** [comment]
Yeah I broke the enhance filters unfortunately.. thinking if I need to send a hotfix for it

**Comment by fribbels** [comment]
Version 1.6.1 resolves this, closing
https://github.com/fribbels/Fribbels-Epic-7-Optimizer/releases/tag/v1.6.1
