### ISSUE TITLE
MAC: Java child process exited with code 143

### ISSUE THREAD

**Issue by JoelTheSoul** [fribbels/Fribbels-Epic-7-Optimizer#62]
I've already attempted reinstalling Java

Console error on startup
<img width="537" alt="Screen Shot 2021-03-20 at 8 56 26 PM" src="https://user-images.githubusercontent.com/71058484/111891201-14767b00-89bf-11eb-9664-cd16df319b47.png">

When I click 'Start Scanning'
<img width="939" alt="Screen Shot 2021-03-20 at 8 56 00 PM" src="https://user-images.githubusercontent.com/71058484/111891191-fe68ba80-89be-11eb-9539-15276d3f364a.png">

<img width="544" alt="Screen Shot 2021-03-20 at 8 56 43 PM" src="https://user-images.githubusercontent.com/71058484/111891205-22c49700-89bf-11eb-90f8-29558327709c.png">

**Comment by fribbels** [comment]
Looking into it - seems to be related to the OCR tool

**Comment by fribbels** [comment]
For anyone else having this issue, try using 1.5 until I can send out a fix

**Comment by fribbels** [comment]
Version 1.6.1 fixes this, resolving
https://github.com/fribbels/Fribbels-Epic-7-Optimizer/releases/tag/v1.6.1
