### ISSUE TITLE
Exclude Equipped setting is not saved

### ISSUE THREAD

**Issue by numbahs** [fribbels/Fribbels-Epic-7-Optimizer#66]
The setting isn't saved when moving across units in the optimizer tab.

**Comment by fribbels** [comment]
It sounds like you might have another hidden issue that's the root cause of all these symptoms. Can you share a console log screenshot?

**Comment by numbahs** [comment]
There are no errors in the console log. To be more specific, options such as `Use reforged stats` and `Equipped items` to name a few are saved when switching across heroes via the dropdown menu on the left in the `Optimizer` tab. But `Exclude Equipped` is only saved to your current search, not the search of the hero.

For Example.
1. I am gearing Sigret and want to exclude all equipped items from heroes except LQC
2. I switch over to SSB (Exclude Equipped is still there saying every hero except LQC)
3. I click the X to clear the list of Exclude Equipped units
4. I switch back to Sigret (The Exclude Equipped will be blank still)

Not sure if this is intended or fixable, but it'd be nice.

**Comment by fribbels** [comment]
Its intended to carry over throughout the app - clicking the X will clear it as you've already seen. The intent of the feature is to mark "completed" units as users finish optimizing their units so they don't have to revisit their gear.

**Comment by numbahs** [comment]
Got it. Makes sense, as a user I thought initially that it would be saved just like the rest of the things under options. Maybe make a divide to show it won't be saved? Or do nothing, thought it was a bug though.
