### ISSUE TITLE
Feature Reqeust: A cancel button for search

### ISSUE THREAD

**Issue by numbahs** [fribbels/Fribbels-Epic-7-Optimizer#67]
A cancel button that stops the search in progress short so that I can make a more filtered search, or if it is no longer useful.

**Comment by fribbels** [comment]
There is a cancel button

[https://i.imgur.com/Myh918K.png](https://i.imgur.com/Myh918K.png)

**Comment by numbahs** [comment]
Oh I cannot believe I missed that, sorry lol
