### ISSUE TITLE
In-app editing of gear does not save, disabling antivirus and Run-as-admin does not work

### ISSUE THREAD

**Issue by 1caiser** [fribbels/Fribbels-Epic-7-Optimizer#68]
Trying to edit gear, and followed the in-app popup. No combination of running as admin or disabled antivirus (or both) allows me to edit gear stats. I tried both adding the Fribbels folder to Real-time Protection Exclusions, and turning off Norton's Auto-Protect altogether.

**Comment by fribbels** [comment]
Could you attach screenshots of a console log, by opening dev tools

![https://i.imgur.com/kQjpIyp.png](https://i.imgur.com/kQjpIyp.png)

navigate to the console tab

![https://i.imgur.com/UQoe7mN.png](https://i.imgur.com/UQoe7mN.png)

and then try editing gear again, and screenshot the latest red errors

**Comment by 1caiser** [comment]
Trying it again, Norton gave me a popup about "Data Protector" (it did not do this before). I was then sidetracked, and closed the Optimizer before gathering the logs (my bad). I cannot recreate the error anymore, even after taking the Optimizer off this new Data Protector Exclusions list.

Optimizer works, gear now saves without a hitch.
