### ISSUE TITLE
How do you update?

### ISSUE THREAD

**Issue by FigoFromage** [fribbels/Fribbels-Epic-7-Optimizer#69]
I'm guessing just copy and paste over but I'm afraid it'll have a blank save file that will delete my old one.

Where's the information stored?

**Comment by fribbels** [comment]
Download the new version, unzip it, and it will extract into its own separate folder.

The saves are under your Documents/FribbelsOptimizerSaves folder which are separate from the app files and won't get deleted

**Comment by FigoFromage** [comment]
Thanks for the quick reply!

Also I'm still in awe at your wifi hotspot idea to get the import going. The program is incredible.
