### ISSUE TITLE
Auto Importer Issue

### ISSUE THREAD

**Issue by Alkhriz** [fribbels/Fribbels-Epic-7-Optimizer#71]
Started getting issues with other programs after I installed npcap and python. For example my computer no longer connects to the internet upon start up I always need to "troubleshoot" in order for the computer to fix the issue of it having an, "invalid IP." 
Also my keyboard will randomly stop working, all keys, and usually have to restart in safe mode to get it to work again. I suspect that the issue lies with Npcap, because I've had python on other PCs before and never had any issues, interfering with other programs. Otherwise I have no idea what it could possibly because that's the only thing that's different on my computer since the issues have started. So if anyone has come across a similar issue and has a fix for it it'd be greatly appreciated.

**Comment by fribbels** [comment]
Oh interesting, a couple people mentioned they had trouble with npcap and disconnecting their internet on startup, but I haven't heard of anything about the keyboard/etc. Try uninstalling npcal 1.1 and then installing npcap 1.2 which came out a few weeks ago - that might help?

https://nmap.org/npcap/

**Comment by Alkhriz** [comment]
Confirmed this fixed the issue for me. Uninstalled and reinstalled latest version of npcap and haven't had those issues since.
