### ISSUE TITLE
Feature Request: Main Stat Value priority consideration

### ISSUE THREAD

**Issue by jpanda109** [fribbels/Fribbels-Epic-7-Optimizer#77]
There should be some consideration for how a piece's main stat factors into the filtering process.

As an example, a 45 speed boot might get filtered out depending of the substat priority, whereas a 40 speed boot won't because it has higher valued substats. This, however, ends up with a sub-optimal result when trying to maximize speed.

Possible solution:
Include mainstat of accessories into the substat priority filter. In other words, the mainstat of the item will be added as if it were a fifth substat.
Example:
Consider an atk necklace with 60% atk, 10%hp, 10%def, 10% res, 10% eff. The total substat score would be 100. The substat priority would then compare/sort/filter only against other necklaces.

**Comment by fribbels** [comment]
In 1.7, I've changed the priority filter to consider the main stats as well, basically counting it as a 5th substat
