### ISSUE TITLE
Locked gear still showing in searches

### ISSUE THREAD

**Issue by quippyz** [fribbels/Fribbels-Epic-7-Optimizer#78]
i equipped and locked gear for one hero, then on a new search on other hero the gear still showed up. now the same items are equipped and locked for 2 different heroes

**Comment by fribbels** [comment]
You probably have duplicate gear, try merging your gear.txt again. If that doesn't work, post your gear.txt and .json save file and I'll take a look

**Comment by quippyz** [comment]
yeah sorry, all good, my mistake, didn't completely delete everything before reimporting
