### ISSUE TITLE
I don't know how to fixx this

### ISSUE THREAD

**Issue by Thisidiot** [fribbels/Fribbels-Epic-7-Optimizer#8]
After I finished downloading I wasn't really paying attention too much and now every time I try to redownload it always wants to open with Firefox, I can't unzip no matter how many times I delete and try again. So I kind of need help to get the original download link back.

**Comment by fribbels** [comment]
Try using 7zip https://www.7-zip.org/ to extract https://i.imgur.com/v12R2SH.png
