### ISSUE TITLE
Senya attack value is lower than in-game

### ISSUE THREAD

**Issue by MariothP** [fribbels/Fribbels-Epic-7-Optimizer#80]
When using the optimizer for gear on Senya, the optimizer's attack value seems to always be lower than what I see in game
I've double checked Gunther who has his attack calculated the same way, and the stats for him in the optimizer match in game correctly so this problem is specific to Senya

**Comment by fribbels** [comment]
Yeah Senya's attack can't be fixed without a new version - I've updated it to be release in 1.7
