### ISSUE TITLE
TypeError: Cannot read property "replaced" of undefined

### ISSUE THREAD

**Issue by XsakuranoX** [fribbels/Fribbels-Epic-7-Optimizer#9]
Hi, i followed all the steps and uploaded my gears but this error msg shows up when i try upload, am i doing something wrong?

**Comment by fribbels** [comment]
Can you share a screenshot file?

**Comment by XsakuranoX** [comment]
https://imgur.com/a/NJySjvt
https://imgur.com/a/qicmVrb
Heres the error and the screenshot i tried to upload, thank you very much!

**Comment by fribbels** [comment]
It looks like your pictures are the wrong dimension

https://i.imgur.com/3D71Sno.png

If you're using bluestacks check the workaround here https://github.com/fribbels/Fribbels-Epic-7-Optimizer/commit/94b8730e94e6323b278265ab46f6602ed7822c22#r45552268

**Comment by XsakuranoX** [comment]
Ohh damn i see it now, will play around the setting to see if i can fix it, thx a lot

**Comment by XsakuranoX** [comment]
Damn i figured out why, i was on an older version of Bluestacks so the screen shots are wrong, Thank you fribbels.
