### ISSUE TITLE
Request: Include Heroes from Waiting Room in Auto-import

### ISSUE THREAD

**Issue by rlad78** [fribbels/Fribbels-Epic-7-Optimizer#92]
So I'm not sure if this is a feature that has just been overlooked, or if it's something much more difficult to implement when capturing the character data on login. If it's the latter, or if this was discussed elsewhere and I just didn't see it, please feel free to close this out. 

If it isn't too difficult however, would it be possible to add in the option of importing 5*/6* units from the Waiting Room? I know I can't speak for everyone, but I often use the Waiting Room as a place to keep units that have potential but aren't geared-up.

**Comment by fribbels** [comment]
The waiting room is unfortunately kept in a separate data structure than the heroes list. Could you add them in manually once, then use the "Import only optimizer heroes" option to keep the updated?

**Comment by rlad78** [comment]
Absolutely no worries at all. I figured that was probably the issue. I've
moved my heroes to my main list and already imported them that way. Thanks,
you can close this now c:
